### ISSUE TITLE
"Route dispatch never rendered"

### ISSUE THREAD

**Issue by SylvainBigonneau** [nxio/meteor-flash#4]
Apparently the flash package provokes a serious error with the new version of iron:router.

[See my ticket here](https://github.com/EventedMind/iron-router/issues/1005).

**Comment by bachly** [comment]
Hi Christian,

I got this error again. 

In contrast to Mattray, I need it to be the other way round.

e.g. 

From 

Router.onBeforeAction(function () { Flash.clear(); this.next(); });

To 

Router.onBeforeAction(function () { Flash.clear(); });

I got this error:

Exception in defer callback: TypeError: this.next is not a function
